### ISSUE TITLE
Arch Install

### ISSUE THREAD

**Issue by angel-ayala** [kengz/SLM-Lab#140]
Hi, i'm having trouble in the installation because the linux distro, can you indicate the packages required for a correct installation for run the "yarn install" command.

It's look a great framework and i'll like to test it, thanks and regards.

**Comment by raymondchua** [comment]
Hi @angel-ayala , I think it is in this file:
https://github.com/kengz/SLM-Lab/blob/master/environment.yml

**Comment by angel-ayala** [comment]
oh great, thanks.

**Comment by kengz** [comment]
@angel-ayala Additionally you need to go through the steps in https://github.com/kengz/SLM-Lab/blob/master/bin/setup_ubuntu and tweak the package installer command to what's needed for Arch. There are required system level dependencies other than Conda

**Comment by angel-ayala** [comment]
effectively @kengz , i did it changing the packages name and the corresponding installer (pacman in my case), i create the script setup_arch and modify the setup file for checking if is arch distro to run the installer, i can submit the files if you're interest.

**Comment by kengz** [comment]
Would love to have a version! Could u commit it? All setups scripts are conditionally called from a main setup script `bin/setup` by checking the old version.

**Comment by kengz** [comment]
if you'd like to pick up some Github workflow, I'd recommend this guide: https://github.com/openpnp/openpnp/wiki/Your-First-Pull-Request

Otherwise, feel free to just post the script's content here and I'll add it. Wrap text with triple ticks \` to make it easier for me to copy without formatting; it'll look like:
```
example
code
```

**Comment by angel-ayala** [comment]
thanks, the link was very useful
