### ISSUE TITLE
Atari memory preprocessing crops out part of game space

### ISSUE THREAD

**Issue by tonyzhang25** [kengz/SLM-Lab#228]
Problem with image preprocessing for Atari games where part of the game space at the top is being cropped out.

State output from OpenAI for certain games (e.g. breakout) has a banner of unused pixels on the bottom. When cropping to 84x84, part of the top state space is missing, and extra unused pixels on the bottom are preserved. This is especially problematic for pong, where the paddle itself could be occluded.

See raw game image (breakout):
![preprocessed_state](https://user-images.githubusercontent.com/17558426/48160845-d4028080-e28d-11e8-99b0-1903a2c80842.png)

See preprocessed game state (breakout):
![memory_state_visuals4](https://user-images.githubusercontent.com/17558426/48160857-da90f800-e28d-11e8-9b60-be72744a3258.png)

**Comment by kengz** [comment]
Thanks for reporting this. And nice catch! That evaded our occasional inspection for a long time. Addressing this now
