### ISSUE TITLE
Running inside Google Colab

### ISSUE THREAD

**Issue by philwinder** [kengz/SLM-Lab#373]
I'm attempting to get SLM-Lab working inside a Google Colab instance. I can't get the getting started example working because of a torch error.

**To Reproduce**
[Run this notebook](https://colab.research.google.com/gist/philwinder/42a41a6db5e1b40aec0e5211efe1f171/untitled5.ipynb)

**Error logs**
```shell
Traceback (most recent call last):
  File "run_lab.py", line 77, in <module>
    mp.set_start_method('spawn')  # for distributed pytorch to work
  File "/usr/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

I think the solution is to add some exception handling around the `mp.set_start_method('spawn')` call, but I'm not certain about that.

Thanks!

**Comment by kengz** [comment]
We've never ran it on colab notebook, thanks for trying this out! Seem like the runtime is different than when running from a plain bash shell. I'll push a patch for this
