### ISSUE TITLE
how can i run my own environment with "search" mode

### ISSUE THREAD

**Issue by lidongke** [kengz/SLM-Lab#378]
when i run my own e, thienvironment with "search" mode report en error that : my own environment has not register ,(i.e my environment named war3),i think it is because it startup the ray and skip to import war3, but i do not know where should i do " import war3" ,i do this in run_lab.py get the error, but i do this in openai.py ,this error can be resolved.
in slm_lab/env/openai.py like this:
 
from slm_lab.env.base import BaseEnv
from slm_lab.env.wrapper import make_gym_env
from slm_lab.env.vec_env import make_gym_venv
from slm_lab.env.registration import try_register_env
from slm_lab.lib import logger, util
from slm_lab.lib.decorator import lab_api
import gym
import numpy as np
import pydash as ps
import roboschool
import war3

logger = logger.get_logger(__name__)
can i import it in my python or run_lab.py , not in your source code?
@kengz 
@lgraesser

**Comment by kengz** [comment]
Hi, the registration problem is specific to new environment not being registered.

Importing it in `openai.py` is correct if you environment self-registers, just like how `roboschool` self-registers when imported there. If you need to register the environment under openai gym, like [how vizdoom was registered](https://github.com/kengz/SLM-Lab/blob/master/slm_lab/env/registration.py#L16-L27).

**Comment by kengz** [comment]
@lidongke seemed like you got search to run. is this issue good to close?

**Comment by lidongke** [comment]
you can close this issue,thanks~@ kengz
