### ISSUE TITLE
every trial startup NUM_EVAL envs

### ISSUE THREAD

**Issue by lidongke** [kengz/SLM-Lab#379]
if i have an empty _random_baseline.json, every trial will startup NUM_EVAL envs to compute random_baseline at the same time, but this has a problem,  my CPU memory can not allow so many envs, it will crash. 
i.e NUM_EVAL = 20
    max_trial = 4
  it will startup 80 envs when eval !
Am i right ?
How can i resolve this?
@kengz 
@lgraesser

**Comment by kengz** [comment]
You just need to fill in your entry in the json file first if you know what's the number, then it will skip the eval. This can be done manually by directly modifying the json file, or running [this script](https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/random_baseline.py#L2).

**Comment by kengz** [comment]
@lidongke did you resolve this issue?

**Comment by lidongke** [comment]
you can close this issue,thanks~@ kengz
