### ISSUE TITLE
how can i effective use my CPU resource?

### ISSUE THREAD

**Issue by lidongke** [kengz/SLM-Lab#385]
Hi~

If  i have 20 CPUS, 10 envs, 5 sessions, then it will starup 50 process with 20 CPUS, i consider it is not reasonable, am i right ? how can i fullly and reasonable use my CPU resource?
@kengz

**Comment by kengz** [comment]
hi, let's move this to #384 to discuss resource allocation in general

**Comment by kengz** [comment]
@lidongke you can now specify `num_cpus` and `num_gpus` per trial directly under the `meta` spec
