### ISSUE TITLE
Run without roboschool

### ISSUE THREAD

**Issue by ThGravo** [kengz/SLM-Lab#428]
Is it possible to run without roboschool? On the server I'm using installing roboschool fails, but it seems the code depends on it although I'm not trying to run an environment from roboschool.

**Comment by kengz** [comment]
Hi @ThGravo , you can just comment them out on your local version of the repo: They occur at these locations: https://github.com/kengz/SLM-Lab/search?q=%22import+roboschool%22&unscoped_q=%22import+roboschool%22
