### ISSUE TITLE
Any demo for soft actor critic on discrete action space?

### ISSUE THREAD

**Issue by lihuiknight** [kengz/SLM-Lab#436]
Cool Work.

It seems that you have implemented sac to support discrete action space.
I wonder whether this project contains tiny demo from running soft actor critic on scenario of discrete action space. 

Best,
Ken

**Comment by kengz** [comment]
Hi @lihuiknight, yes, you can [run any spec file using the lab command](https://slm-lab.gitbook.io/slm-lab/using-slm-lab/slm-lab-command).
For this particular case, u can run SAC on LunarLander, which is a discrete environment. For the command:
- spec file, which you can find at: [slm_lab/spec/benchmark/sac/sac_lunar.json](https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/benchmark/sac/sac_lunar.json)
- spec name: "sac_lunar" in the file
- lab mode: "train"

All in all, you can run it with the command
```bash
python run_lab.py slm_lab/spec/benchmark/sac/sac_lunar.json sac_lunar train
```

Benchmark results and graphs can be found [here](https://app.gitbook.com/@slm-lab/s/slm-lab/~/drafts/-Lvq4atwN9gUKSj52nEO/benchmark-results/discrete-benchmark)

**Comment by HafizRiaz** [comment]
> Hi @lihuiknight, yes, you can [run any spec file using the lab command](https://slm-lab.gitbook.io/slm-lab/using-slm-lab/slm-lab-command). For this particular case, u can run SAC on LunarLander, which is a discrete environment. For the command:
> 
>     * spec file, which you can find at: [slm_lab/spec/benchmark/sac/sac_lunar.json](https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/benchmark/sac/sac_lunar.json)
> 
>     * spec name: "sac_lunar" in the file
> 
>     * lab mode: "train"
> 
> 
> All in all, you can run it with the command
> 
> ```shell
> python run_lab.py slm_lab/spec/benchmark/sac/sac_lunar.json sac_lunar train
> ```
> 
> This should train within a few hours on a laptop.
> 
> Benchmark results and graphs can be found [here](https://app.gitbook.com/@slm-lab/s/slm-lab/~/drafts/-Lvq4atwN9gUKSj52nEO/benchmark-results/discrete-benchmark)

Hi dear, 
I have seen your example to deal with discrete actions via Gumbel-SoftMax distribution with SAC . I was surprising if I can use the same trick for my environment which has to simultaneously adjust the set-points of both continuous and discrete devices for voltage control. I have found paper in literature which applies Gumbel-SoftMax distribution with DDPG, but for SAC people mostly use multi-discrete SAC or some other approaches. Would you plz give your kind suggestions about applying SAC with Gumbel-SoftMax distribution
