### ISSUE TITLE
Why is kengz's name appearing side by side with the indian youtube scammer Siraj Raval in the SLM Lab paper?

### ISSUE THREAD

**Issue by archywillhe** [kengz/SLM-Lab#458]
So I stumbled upon this paper titled SLM Lab https://drive.google.com/file/d/0BwUv84lNDk72Q1gzaXgwR2U3U2NWVlZSOFk4amZIRmV1QXI0/view  

Haven't read it. 

But I saw kengz's name right next to Siraj Raval, the notorious indian youtube scammer that I really dislike.

Why is kengz's name appearing side by side with the indian youtube scammer? Is this a bug?

The link to the paper is found in https://www.youtube.com/channel/UCWN3xxRkmTPmbKwht9FuE5A/about

**Comment by kengz** [comment]
Hi,

I understand your concern. Before the plagiarism scandal with Siraj we had a short collaboration for School of AI to use SLM Lab for Deep RL education and research, hence this white paper with his name on it. To be clear, his did not contribute to the development of the lab, as you can see in the Github contributors, rather his role was on promoting it to the students of School of AI.

Regrettably, we all knew what happened next. School of AI swiftly cut ties with him. Like a number of people/institutions who have collaborated with Siraj (hence leading to his seeming credibility), we too renounced him and quickly distanced ourselves, and also pulled down this paper. However his own copy remains up on his channel which we have no control over.

Hope this makes it clear.

If you're looking for the official SLM Lab paper, please refer to this on arxiv:  https://arxiv.org/abs/1912.12482
