### ISSUE TITLE
book branch: unable to run initial example

### ISSUE THREAD

**Issue by andrei-radulescu-banu** [kengz/SLM-Lab#473]
After purchasing the book, I've installed the code on both Centos 7 and Ubuntu 18.04. Running the initial example gives a missing library error.

```
./bin/setup
conda activate lab
python run_lab.py slm_lab/spec/demo.json dqn_cartpole dev
```

Gives the error below:

```
    from roboschool  import cpp_household   as cpp_household
ImportError: libpcre16.so.3: cannot open shared object file: No such file or directory
```

You can easily reproduce by doing  `import roboschool` in python in the venv set up for the sandbox.

**Comment by kengz** [comment]
Hi. That's a common error from the gym installation. Could you check #464 for solution?

**Comment by kengz** [comment]
Deferred to linked issue above for solution.
