### ISSUE TITLE
Cannot open shared object file: No such file or directory when running demo

### ISSUE THREAD

**Issue by ChadMcintire** [kengz/SLM-Lab#491]
**Describe the bug**
Program does not run and just errors out.
     from roboschool  import cpp_household   as cpp_household
ImportError: libpcre16.so.3: cannot open shared object file: No such file or directory 

This error comes up when you try to run the run_lab.py

**To Reproduce**
1. OS and environment: Ubuntu 20
2. SLM Lab git SHA (run `git rev-parse HEAD` to get it): ae6787ceb003490ef547d8418fe79628ae393a8c
3. `spec` file used: run_lab.py

**Additional context**

The solution is referenced here: https://github.com/openai/roboschool/issues/193
This is here solution is here: https://zoomadmin.com/HowToInstall/UbuntuPackage/libpcre3-dev

On Ubuntu just need: 
    sudo apt-get install -y libpcre3-dev

**Error logs**
```shell
#REPLACE ME
```

**Comment by kengz** [comment]
Hi thanks for the report. So, is the issue resolved by running `sudo apt-get install -y libpcre3-dev` to install the roboschool dependency? If so we can close this out.

**Comment by kengz** [comment]
closing as resolved
