### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by luckywlj** [kengz/SLM-Lab#495]
When I want to run SLM lab commands according to Page 193 in Chinese version, there is an error information as follows:

(lab) myhost@luckywlj:~/SLM-Lab$ python run_lab.py slm_lab/spec/benchmark/a2c/a2c_nstep_pong.json a2c_ntep_pong search
Traceback (most recent call last):
  File "run_lab.py", line 4, in <module>
    from slm_lab.experiment import search
  File "/home/luckywlj/SLM-Lab/slm_lab/experiment/search.py", line 2, in <module>
    from slm_lab.lib import logger, util
  File "/home/luckywlj/SLM-Lab/slm_lab/lib/logger.py", line 1, in <module>
    from slm_lab.lib import util
  File "/home/luckywlj/SLM-Lab/slm_lab/lib/util.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

I don't know what is the cv2 package, so I try to "pip3 install cv2" and failed. Could you please tell me how to solve the problem? thank you !

**Comment by kengz** [comment]
Hi it's likely that your environment setup failed halfway. Could you show the output from:
```bash
conda activate lab
conda list
```

**Comment by luckywlj** [comment]
![2021-12-05 09-51-21 的屏幕截图](https://user-images.githubusercontent.com/53700751/144730409-f3657be3-5a6a-438d-b268-6709758e2e02.png)

**Comment by luckywlj** [comment]
![2021-12-05 09-51-21 的屏幕截图](https://user-images.githubusercontent.com/53700751/144730476-673b583e-a7ae-4cdc-87bb-f96028978eb4.png)

**Comment by luckywlj** [comment]
> Hi it's likely that your environment setup failed halfway. Could you show the output from:
> 
> ```shell
> conda activate lab
> conda list
> ```

luckywlj@my-pc:~/ai_lib/examples$ conda activate lab
(lab) luckywlj@my-pc:~/ai_lib/examples$ conda list
# packages in environment at /home/luckywlj/anaconda3/envs/lab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2021.10.26           h06a4308_2                      defaults
certifi                            2021.10.8              py37h06a4308_0           defaults
libedit                        3.1.20210910         h7f8727e_0                      defaults
libffi                                 3.2.1                      hf484d3e_1007              defaults
libgcc-ng                       9.1.0                       hdf63c60_0                     defaults
libstdcxx-ng                 9.1.0                       hdf63c60_0                     defaults
ncurses                           6.3                          h7f8727e_2                     defaults
openssl                         1.1.1l                       h7f8727e_0                     defaults
pip                                 21.2.2                       py37h06a4308_0          defaults
python                            3.7.3                      h0371630_0                    defaults
readline                          7.0                          h7b6447c_5                    defaults
setuptools                   58.0.4                      py37h06a4308_0          defaults
sqlite                             3.33.0                       h62c20be_0                   defaults
tk                                    8.6.11                       h1ccaba5_0                    defaults
wheel                            0.37.0                      pyhd3eb1b0_1               defaults
xz                                     5.2.5                        h7b6447c_0                    defaults
zlib                                  1.2.11                     h7b6447c_3                     defaults

**Comment by luckywlj** [comment]
> Hi it's likely that your environment setup failed halfway. Could you show the output from:![2021-12-05 09-51-21 的屏幕截图](https://user-images.githubusercontent.com/53700751/144730683-1ad8e56b-2485-4538-ba3e-2ae6e50ee213.png)> 
> ```shell
> conda activate lab
> conda list
> ```

![2021-12-05 09-51-21 的屏幕截图](https://user-images.githubusercontent.com/53700751/144730686-83407138-65ca-4b6f-8204-44c5ecad8fa1.png)

**Comment by luckywlj** [comment]
![2021-12-05 09-51-21 的屏幕截图](https://user-images.githubusercontent.com/53700751/144730713-9b63da3c-a42f-4972-8f43-cc113a8b99b8.png)

**Comment by kengz** [comment]
yep it's missing a lot of dependencies. Could you run this from the SLM Lab folder: `conda env update -f environment.yml`
That should set things up. Then you should be able to use it.

**Comment by luckywlj** [comment]
> yep it's missing a lot of dependencies. Could you run this from the SLM Lab folder: `conda env update -f environment.yml` That should set things up. Then you should be able to use it.

thank you so much! I try it now.

**Comment by luckywlj** [comment]
I didn't follow the install step   cd SLM-Lab/   then   ./bin/setup because I look into the file setup ,Anaconda need be install.  I had installed Anaconda and used it conda some virtual environments. There are some experiments on these envs. So I
