### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by luckywlj** [kengz/SLM-Lab#497]
I follow the install instructions to install the miniconda. But when I follow the Quick Start to  run test command"python run_lab.py slm_lab/spec/demo.json dqn_cartpole dev", there are some error information as follows:
![2021-12-05 21-35-14 的屏幕截图](https://user-images.githubusercontent.com/53700751/144748963-8bd8a4dd-8ebf-4011-a599-7a31d92f5bb1.png)

BTW: yesterday I have asked the problem about the installation. Because I had ever installed anaconda and configure some envs to run other experiments. So I don't run "/bin/setup" instead of  run commands as follows:
conda env update -f environment.yml
source ~/.bashrc

the two commands is from SLM_Lab/bin/setup_ubuntu. 
I don't want to affect the original anaconda because of running setup.py.
But this failed. So I uninstall the anaconda and operate the installation process according to  the installation guide.

Could you help me to solve the problem?

**Comment by kengz** [comment]
it can't find the `.git` file, so that means the folder wasn't a cloned git repo. Could you git clone using the first step in the guide: https://slm-lab.gitbook.io/slm-lab/setup/installation

**Comment by luckywlj** [comment]
Yes, I don't use git clone because github is not available on campus network. I use chrome to access github through proxy. So I download the zip package from github and unzip the code repository. So it is basically impossible to download successfully with git clone. What should I do in this situation?

**Comment by kengz** [comment]
I see. In that case you can comment out this line on your local file: https://github.com/kengz/SLM-Lab/blob/master/slm_lab/spec/spec_util.py#L134
also we've just released an update yesterday with fixes for GPU so you may want to redownload too.

**Comment by luckywlj** [comment]
Thank you very  much! Now it is ok!
