### ISSUE TITLE
I have encounter one problem, maybe a bug.

### ISSUE THREAD

**Issue by dvstter** [kengz/SLM-Lab#506]
I've designed a MultiDiscrete observation and action space. But when I employ DDQN on this environment, the compiler tells me that 'assert len(in_dim) == 3' wrong in 'net/conv.py'. I found that the in_dim is 3, which is an integer. The problem seems happen in function '_get_observable_dim(self, observation_space)' in 'env/base.py'. The observation_space.shape will not return the actual shape, but the dim when the environment is MultiDiscrete. Another verification is that in function '_get_action_dim', action_dim is processed in this way, which is 'action_space.nvec.tolist()'. So I change put two lines of code below
`
if instance(observation_space, spaces.MultiDiscrete):
    state_dim = observation_sapce.nvec.tolist()
` in line 145-146 in file env/base.py.
![A8B6CD68EC4E12E572A1DFF4395202FB](https://user-images.githubusercontent.com/11886450/161076046-73221dca-cc59-47dc-9cec-2ea67d4537c8.jpg)

**Comment by kengz** [comment]
Hi @dvstter thanks for the ticket. Would you mind opening a pull request to add those 2 lines of code?
